// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class TestBase
    {
        public static IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        protected string BaseUrl;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
            BaseUrl = "http://20.50.171.10:8080";
            driver.Navigate().GoToUrl(BaseUrl);
            driver.Manage().Window.Size = new System.Drawing.Size(1440, 817);
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
    }
}