      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public static class AddNewPetTypePage
    {
        public static IWebElement addPetButton => TestBase.driver.FindElement(By.CssSelector(".addPet"));
        public static IWebElement petTypeNameField => TestBase.driver.FindElement(By.Id("name"));

        public static void changeNameAndSave(IWebElement element, string text){
            element.Click();
            element.SendKeys(text);
            TestBase.driver.FindElement(By.CssSelector(".saveType")).Click();
        }

    }
}