      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public static class AddNewVisitPage
    {
        public static IWebElement descriptionField => TestBase.driver.FindElement(By.Id("description"));

        public static void chooseDate(){
            TestBase.driver.FindElement(By.Name("date")).Click();
            TestBase.driver.FindElement(By.CssSelector("path")).Click();
            TestBase.driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).Click();
        }

    }
}