      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class AddNewVisitPage: Pages
    {
        public AddNewVisitPage(IWebDriver driver) : base(driver) {}
        public IWebElement descriptionField => driver.FindElement(By.Id("description"));
        public IWebElement date => driver.FindElement(By.Name("date"));

        public void chooseDate(String newDate){
            date.Click();
            date.Clear();
            date.SendKeys(newDate);
            // driver.FindElement(By.CssSelector("path")).Click();
            // driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).Click();
        }

    }
}