      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class BasePage
    {
        protected IWebDriver driver;
        public BasePage(IWebDriver driver) => this.driver = driver;
    }
}