      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class EditOwnerPage: BasePage
    {
        public EditOwnerPage(IWebDriver driver) : base(driver) {}
        public IWebElement phoneField => driver.FindElement(By.Id("telephone"));
        public IWebElement firstName => driver.FindElement(By.Id("firstName"));
        public IWebElement lastName => driver.FindElement(By.Id("lastName"));
        public IWebElement updateOwnerButton => driver.FindElement(By.CssSelector(".updateOwner"));
    }
}