      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public static class EditOwnerPage
    {
        public static IWebElement phoneField => TestBase.driver.FindElement(By.Id("telephone"));
        public static IWebElement updateOwnerButton => TestBase.driver.FindElement(By.CssSelector(".updateOwner"));

        public static void ClearAndType(IWebElement element, string text){
            element.Click();
            element.SendKeys(text);
        }

    }
}