      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class Pages
    {
        protected IWebDriver driver;
        public Pages(IWebDriver driver) => this.driver = driver;
        public EditOwnerPage EditOwner => new EditOwnerPage(driver);
        public AddNewVisitPage AddNewVisit => new AddNewVisitPage(driver);
        public AddNewPetTypePage AddNewPetType => new AddNewPetTypePage(driver);
        public NavigationComponent Navigation => new NavigationComponent(driver);
    }
}