// // Generated by Selenium IDE
// using System;
// using OpenQA.Selenium;
// using OpenQA.Selenium.Support.UI;
// using OpenQA.Selenium.Interactions;
// using NUnit.Framework;
// using SeleniumExtras.WaitHelpers;

// namespace PetClinicTestProject
// {
//     public class AddnewpettypeTest : TestBase
//     {
//         [Test]
//         public void addnewpettype()
//         {
//             driver.FindElement(By.CssSelector("li:nth-child(4) > a")).Click();
//             {
//                 var element = driver.FindElement(By.CssSelector("li:nth-child(4) > a"));
//                 Actions builder = new Actions(driver);
//                 builder.MoveToElement(element).Perform();
//             }
//             var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            
//             driver.FindElement(By.CssSelector("tr:nth-child(6) .editPet")).Click();
//             driver.FindElement(By.CssSelector("app-pettype-edit > .container-fluid")).Click();
//             AddNewPetTypePage.petTypeNameField.Clear();
//             AddNewPetTypePage.petTypeNameField.SendKeys("gggggg");
//             driver.FindElement(By.CssSelector(".updatePetType")).Click();
//             wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".addPet")));
//             AddNewPetTypePage.addPetButton.Click();
//             {
//                 Actions builder = new Actions(driver);
//                 builder.MoveToElement(AddNewPetTypePage.addPetButton).Perform();
//             }
//             AddNewPetTypePage.changeNameAndSave(AddNewPetTypePage.petTypeNameField, "new pet type");
//             Assert.That(driver.FindElement(By.CssSelector("tr:nth-last-child(1) > td > input")).GetAttribute("ng-reflect-model"), Is.EqualTo("new pet type"));
//         }
//     }
// }