// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;
using NUnit.Allure.Attributes;

namespace PetClinicTestProject
{
    [TestFixture]
    public class EditOwnerTest : TestBase
    {
        [Test]
        [AllureSuite("Check edit owners functionality")]

        public void editOwner()
        {
            pages.Navigation.OwnerTab.Click();
            {
                var element = driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.CssSelector("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            pages.Navigation.OwnerListLink.Click();
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".petOwner:nth-child(66) a")));
            Helpers.ScrollToBottom(driver, ".petOwner:nth-child(66) a");
            driver.FindElement(By.CssSelector(".petOwner:nth-child(66) a")).Click();
            driver.FindElement(By.CssSelector(".editOwner")).Click();

            var phoneNumber = Faker.RandomNumber.Next(1000000000, 9999999999).ToString();
            var ownerName = Owners.OwnerList[0].Name;
            var ownerSurname = Owners.OwnerList[0].Surname;

            Helpers.ClearAndType(pages.EditOwner.firstName, ownerName);
            Helpers.ClearAndType(pages.EditOwner.lastName, ownerSurname);
            Helpers.ClearAndType(pages.EditOwner.phoneField, phoneNumber);
            
            pages.EditOwner.updateOwnerButton.Click();
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".ownerPhone")));
            Assert.That(driver.FindElement(By.CssSelector(".ownerPhone")).Text, Is.EqualTo(phoneNumber));
        }
    }
}