// // Generated by Selenium IDE
// using System;
// using System.Collections.Generic;
// using OpenQA.Selenium;
// using OpenQA.Selenium.Chrome;
// using OpenQA.Selenium.Support.UI;
// using OpenQA.Selenium.Interactions;
// using NUnit.Framework;
// using SeleniumExtras.WaitHelpers;

// namespace PetClinicTestProject
// {
//     [TestFixture]
//     public class EditOwnerTest : TestBase
//     {
//         [Test]
//         public void editOwner()
//         {
//             driver.FindElement(By.CssSelector(".ownerTab")).Click();
//             {
//                 var element = driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)"));
//                 Actions builder = new Actions(driver);
//                 builder.MoveToElement(element).Perform();
//             }
//             {
//                 var element = driver.FindElement(By.CssSelector("body"));
//                 Actions builder = new Actions(driver);
//                 builder.MoveToElement(element, 0, 0).Perform();
//             }
//             driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
//             var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
//             wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".petOwner:nth-child(66) a")));
//             {
//                 var element = driver.FindElement(By.CssSelector(".petOwner:nth-child(66) a"));
//                 Actions builder = new Actions(driver);
//                 builder.MoveToElement(element, 0, 0).Perform();
//             }
//             driver.FindElement(By.CssSelector(".petOwner:nth-child(66) a")).Click();
//             driver.FindElement(By.CssSelector(".editOwner")).Click();
//             EditOwnerPage.ClearAndType(EditOwnerPage.phoneField, "1241241241");
//             EditOwnerPage.updateOwnerButton.Click();
//             wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".ownerPhone")));
//             Assert.That(driver.FindElement(By.CssSelector(".ownerPhone")).Text, Is.EqualTo("1241241241"));
//         }
//     }
// }