      // Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace PetClinicTestProject
{
    public class NavigationComponent
    {
        protected IWebDriver driver;
        public NavigationComponent(IWebDriver driver) => this.driver = driver;

        public IWebElement OwnerTab => driver.FindElement(By.CssSelector(".ownerTab"));

        public IWebElement OwnerListLink => driver.FindElement(By.CssSelector(".open li:nth-child(1) > a"));
    }
}